#!/usr/bin/env bash

# Install nginx if it's not already installed
if ! command -v nginx &> /dev/null
then
    apt-get update
    apt-get install -y nginx
fi

# Set nginx user to nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Configure nginx to listen on all active IPs on port 8080
sed -i '/listen \[::\]:80 default_server;/a \\tlisten [::]:8080 default_server;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server;/a \\tlisten 8080 default_server;' /etc/nginx/sites-available/default

# Restart nginx service
service nginx restart

